files:
- generatedChecksum: 39FF52903D784BEF79D3640DC1072AFA
  logicalPath: config\pic32mz_das_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 39FF52903D784BEF79D3640DC1072AFA
- generatedChecksum: D9A813E2A5A37439D871B815146CFF09
  logicalPath: config\pic32mz_das_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D9A813E2A5A37439D871B815146CFF09
- generatedChecksum: 3F734BF05F77A6A15923D26C72B16BB5
  logicalPath: config\pic32mz_das_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3F734BF05F77A6A15923D26C72B16BB5
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: A6B00E78CB9B1F4229F94811BB42AB56
  logicalPath: config\pic32mz_das_sk\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: A6B00E78CB9B1F4229F94811BB42AB56
- generatedChecksum: 1F19DD53C12B0F7628B7A8AA1C18050F
  logicalPath: config\pic32mz_das_sk\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1F19DD53C12B0F7628B7A8AA1C18050F
- generatedChecksum: 3DEB4AE7CD7A32AD203A68B750A81AFF
  logicalPath: config\pic32mz_das_sk\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3DEB4AE7CD7A32AD203A68B750A81AFF
- generatedChecksum: C3ADE3F4E8EFC95E72D5A81131B0839B
  logicalPath: config\pic32mz_das_sk\peripheral\tmr1
  name: plib_tmr1.c
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: SOURCE
  userChecksum: C3ADE3F4E8EFC95E72D5A81131B0839B
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mz_das_sk\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: D6CA782ABE1EA0BA4F7ADEA9CF3B0CC8
  logicalPath: config\pic32mz_das_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: D6CA782ABE1EA0BA4F7ADEA9CF3B0CC8
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mz_das_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mz_das_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mz_das_sk\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 44A9EFA06536DE1713738D859242B11C
  logicalPath: config\pic32mz_das_sk\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 44A9EFA06536DE1713738D859242B11C
- generatedChecksum: F10BCB05835F6FE9EDC2B2ED2E45AF63
  logicalPath: config\pic32mz_das_sk\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: F10BCB05835F6FE9EDC2B2ED2E45AF63
- generatedChecksum: 32D7539D9231F3C159ABECE91A0281EA
  logicalPath: config\pic32mz_das_sk\peripheral\tmr1
  name: plib_tmr1.h
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 32D7539D9231F3C159ABECE91A0281EA
- generatedChecksum: 69E7C8CDAB1B32838331EE261170CEA4
  logicalPath: config\pic32mz_das_sk\peripheral\tmr1
  name: plib_tmr1_common.h
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 69E7C8CDAB1B32838331EE261170CEA4
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\pic32mz_das_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: C80077C804F75407DD1AAC6C0E5422E3
  logicalPath: config\pic32mz_das_sk
  name: p32MZ2064DAS169.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C80077C804F75407DD1AAC6C0E5422E3
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_das_sk;../src/packs/PIC32MZ2064DAS169_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_das_sk;../src/packs/PIC32MZ2064DAS169_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
