configName: pic32mz_das_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MZ2064DAS169
projectName: ''
settings:
  PackageFilter: csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.4.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ_DA_DFP\0.1\PIC32MZDA\atdf\PIC32MZ2064DAS169.atdf
