files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/pic32mz_dag_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: 327B0804108C048B6C6D2B0FED2532BB
  logicalPath: config/pic32mz_dag_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 327B0804108C048B6C6D2B0FED2532BB
- generatedChecksum: 731A138A1623AEA258E586598F8A498A
  logicalPath: config/pic32mz_dag_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 731A138A1623AEA258E586598F8A498A
- generatedChecksum: null
  logicalPath: ''
  name: main_mzda.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 7203D09C52ECE93821EC2153BC834678
  logicalPath: config/pic32mz_dag_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7203D09C52ECE93821EC2153BC834678
- generatedChecksum: B8B6CA615EBA919FEB4A8B550B0DE541
  logicalPath: config/pic32mz_dag_sk/peripheral/cmp
  name: plib_cmp.c
  physicalPath: peripheral/cmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: B8B6CA615EBA919FEB4A8B550B0DE541
- generatedChecksum: BF3120FEEA787A31DE2117BDF5DCD6BD
  logicalPath: config/pic32mz_dag_sk/peripheral/cvr
  name: plib_cvr.c
  physicalPath: peripheral/cvr
  security: NON_SECURE
  type: SOURCE
  userChecksum: BF3120FEEA787A31DE2117BDF5DCD6BD
- generatedChecksum: D29C521AD978DF61F321B88D350ED5F4
  logicalPath: config/pic32mz_dag_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: D29C521AD978DF61F321B88D350ED5F4
- generatedChecksum: 02D028CDB2AE6E57A0339A7F38DF3E6C
  logicalPath: config/pic32mz_dag_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 02D028CDB2AE6E57A0339A7F38DF3E6C
- generatedChecksum: 520BA50DCF33386ACEC05954CA92E6BC
  logicalPath: config/pic32mz_dag_sk/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 520BA50DCF33386ACEC05954CA92E6BC
- generatedChecksum: F8E5A602361062C584BFD545E44A2C6F
  logicalPath: config/pic32mz_dag_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8E5A602361062C584BFD545E44A2C6F
- generatedChecksum: F8749956EA60A4932A96820B1FD60963
  logicalPath: config/pic32mz_dag_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F8749956EA60A4932A96820B1FD60963
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_dag_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_dag_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_dag_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: F75B761F135981B29C3DF4247705D7A1
  logicalPath: config/pic32mz_dag_sk/peripheral/cmp
  name: plib_cmp.h
  physicalPath: peripheral/cmp
  security: NON_SECURE
  type: HEADER
  userChecksum: F75B761F135981B29C3DF4247705D7A1
- generatedChecksum: 519595A71797770B586ED17BE1FE4584
  logicalPath: config/pic32mz_dag_sk/peripheral/cvr
  name: plib_cvr.h
  physicalPath: peripheral/cvr
  security: NON_SECURE
  type: HEADER
  userChecksum: 519595A71797770B586ED17BE1FE4584
- generatedChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
  logicalPath: config/pic32mz_dag_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
- generatedChecksum: FFF8E458FD7BB6E5CED45D1549F80253
  logicalPath: config/pic32mz_dag_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: FFF8E458FD7BB6E5CED45D1549F80253
- generatedChecksum: ABEBE7D57FD85725DCF9E71E09924F4A
  logicalPath: config/pic32mz_dag_sk/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: ABEBE7D57FD85725DCF9E71E09924F4A
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mz_dag_sk/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_dag_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: 2DFEBDAC10E5184CF73C0A556D82F993
  logicalPath: config/pic32mz_dag_sk
  name: p32MZ2064DAG169.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 2DFEBDAC10E5184CF73C0A556D82F993
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_dag_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_dag_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
