files:
- generatedChecksum: 39FF52903D784BEF79D3640DC1072AFA
  logicalPath: config\pic32mz_daa_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 39FF52903D784BEF79D3640DC1072AFA
- generatedChecksum: 6EEDB403DA475B15D559455BBD72F027
  logicalPath: config\pic32mz_daa_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6EEDB403DA475B15D559455BBD72F027
- generatedChecksum: AD3CC15B64C709360E39C687245DD8D5
  logicalPath: config\pic32mz_daa_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AD3CC15B64C709360E39C687245DD8D5
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 40137C6ECDB1649B6EC33C4AA77AD5E5
  logicalPath: config\pic32mz_daa_sk\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 40137C6ECDB1649B6EC33C4AA77AD5E5
- generatedChecksum: AEEEEE203190423C2C13EE4EB96F909F
  logicalPath: config\pic32mz_daa_sk\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: AEEEEE203190423C2C13EE4EB96F909F
- generatedChecksum: 746A22976CA4CDE5425CC027498A8274
  logicalPath: config\pic32mz_daa_sk\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 746A22976CA4CDE5425CC027498A8274
- generatedChecksum: 44763693752BE58F1A42EFC7156CEF2F
  logicalPath: config\pic32mz_daa_sk\peripheral\sqi
  name: plib_sqi1.c
  physicalPath: peripheral\sqi
  security: NON_SECURE
  type: SOURCE
  userChecksum: 44763693752BE58F1A42EFC7156CEF2F
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mz_daa_sk\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: CA95B623772300D03852ED11F190B788
  logicalPath: config\pic32mz_daa_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CA95B623772300D03852ED11F190B788
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mz_daa_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mz_daa_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mz_daa_sk\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
  logicalPath: config\pic32mz_daa_sk\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
- generatedChecksum: 86A28E96670DA9BAD3A8305D2733C53E
  logicalPath: config\pic32mz_daa_sk\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 86A28E96670DA9BAD3A8305D2733C53E
- generatedChecksum: 83A29BB1714DD4AF71B7176C4A487262
  logicalPath: config\pic32mz_daa_sk\peripheral\sqi
  name: plib_sqi1.h
  physicalPath: peripheral\sqi
  security: NON_SECURE
  type: HEADER
  userChecksum: 83A29BB1714DD4AF71B7176C4A487262
- generatedChecksum: BA2AAEA19E581F59C1E78E73982F7C78
  logicalPath: config\pic32mz_daa_sk\peripheral\sqi
  name: plib_sqi_common.h
  physicalPath: peripheral\sqi
  security: NON_SECURE
  type: HEADER
  userChecksum: BA2AAEA19E581F59C1E78E73982F7C78
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\pic32mz_daa_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: 5906F0B11E695DA24A715499942D3CB0
  logicalPath: config\pic32mz_daa_sk
  name: p32MZ2064DAA288.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 5906F0B11E695DA24A715499942D3CB0
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_daa_sk;../src/packs/PIC32MZ2064DAA288_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_daa_sk;../src/packs/PIC32MZ2064DAA288_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
